# Generated by Django 5.2.8 on 2025-11-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(help_text='Main page content')),
                ('mission', models.TextField(blank=True, help_text='Mission statement')),
                ('guidelines', models.TextField(blank=True, help_text='Community guidelines')),
                ('privacy_policy', models.TextField(blank=True, help_text='Privacy policy')),
                ('terms_of_use', models.TextField(blank=True, help_text='Terms of use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
