# Generated by Django 5.2.8 on 2025-11-16 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('icon', models.CharField(blank=True, help_text='Optional icon/emoji (e.g., 🔍, 📺)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('active', models.BooleanField(default=True, help_text='Show/hide this resource')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pages.resourcecategory')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
